proyectofinalsustentable/apps/productos/urls.py
from django.urls import path 

from . import views

app_name = "productos"

urlpatterns = [
	path("Detalle/", views.detalle, name="detalle"),
	
	# Admin
	path("Admin/Listar/", views.ListarAdmin.as_view(), name="admin_listar"),
	path("Admin/Nuevo/", views.NuevoAdmin.as_view(), name="admin_nuevo"),
	path("Admin/Editar/<int:pk>/", views.EditarAdmin.as_view(), name="admin_editar"),

]

proyectofinalsustentable/proyectofinalsustentable/urls.py
from django.contrib      import admin
from django.contrib.auth import views as auth_views
from django.urls         import path, include 

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.inicio, name="inicio"),
    path('', views.Inicio.as_view(), name="inicio"),

    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_views.logout_then_login, name="logout"),

    # Includes
    path("Producto/", include('apps.productos.urls'))
]

proyectofinalsustentable/apps/productos/models.py
from django.db import models

class Producto(models.Model):
	nombre = models.CharField(max_length=255)
	precio = models.DecimalField(max_digits=9, decimal_places=2)

	class Meta:
		db_table="productos"

	def __str__(self):
		return self.nombre

proyectofinalsustentable/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class Usuario(AbstractUser):
	dni = models.IntegerField(null=True, blank=True)
	# foto = models.ImageField()

	class Meta:
		db_table="usuarios"

	def __str__(self):
		return f"{self.first_name} {self.last_name}"

proyectofinalsustentable/apps/productos/forms.py
from django import forms

from . models import Producto

class ProductoForm(forms.ModelForm):
	nombre = forms.CharField(label="Nombre del Producto", widget=forms.TextInput(attrs={"class": "form-control", "placeholder":"Ingrese nombre del producto"}))

	class Meta:
		model = Producto
		fields = ["nombre", "precio"]

proyectofinalsustentable/apps/productos/views.py
from django.shortcuts          import render
from django.urls               import reverse_lazy
from django.views.generic      import ListView, CreateView 
from django.views.generic.edit import UpdateView

from .forms  import ProductoForm
from .models import Producto

def detalle(request):
	context = {}
	return render(request, "productos/detalle.html", context)


class ListarAdmin(ListView):
	template_name="productos/admin/listar.html"
	model = Producto
	context_object_name="productos"

	
	def get_queryset(self):
		# self.request
		return Producto.objects.all().order_by("id")
	

class NuevoAdmin(CreateView):
	template_name = "productos/admin/nuevo.html"
	model = Producto
	form_class = ProductoForm

	def get_success_url(self, **kwargs):
		return reverse_lazy("productos:admin_listar")

class EditarAdmin(UpdateView):
	template_name = "productos/admin/editar.html"
	model = Producto
	form_class = ProductoForm

	def get_success_url(self, **kwargs):
		return reverse_lazy("productos:admin_listar")
	

proyectofinalsustentable/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

proyectofinalsustentable/proyectofinalsustentable/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView

from apps.productos.models import Producto

"""
# Inicio basado en funcion
def inicio(request):
	context = {
		"productos": Producto.objects.all()
	}
	return render(request, "inicio.html", context)
"""

class Inicio(TemplateView):
	template_name = "inicio.html"

	
	def get_context_data(self, **kwargs):
		context = super(Inicio, self).get_context_data(**kwargs)
		context["productos"] = Producto.objects.all()
		return context
	

proyectofinalsustentable/templates/base/base.html
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>InforMarket</title>

    <!-- Bootstrap core CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  	<body>
		{% include "base/header.html" %}

		<main>
		  	{% include "base/portada.html" %}
		  	<div class="album py-5 bg-light">
		    	<div class="container">

		    		<nav class="navbar navbar-expand-lg navbar-light bg-light">
					  	<div class="container-fluid">
						    <a class="navbar-brand" href="#">MENU</a>
						    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
						      	<span class="navbar-toggler-icon"></span>
						    </button>
						    <div class="collapse navbar-collapse" id="navbarNav">
						      	<ul class="navbar-nav">
							        <li class="nav-item">
							          	<a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
							        </li>
							        <li class="nav-item">
							        	<a class="nav-link" href="#">Catalogo</a>
							        </li>
							        <li class="nav-item">
							        	<a class="nav-link" href="{% url 'productos:admin_listar' %}">Productos</a>
							        </li>
						      	</ul>
						    </div>
					  	</div>
					</nav>



			    	{% block contenido %}
			    	{% endblock contenido %}
			    </div>
		  	</div>

		</main>

		{% include "base/footer.html" %}


		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	</body>
</html>

proyectofinalsustentable/templates/base/footer.html
<footer class="text-muted py-5">
  	<div class="container">
	    <p class="float-end mb-1">
	      <a href="#">Ir al Inicio</a>
	    </p>
	    <p class="mb-1">Sitio desarrollado por la comision 4 del Informatorio</p>

  	</div>
</footer>

proyectofinalsustentable/templates/base/header.html
<header>
	<div class="bg-dark collapse" id="navbarHeader" style="">
	    <div class="container">
	      <div class="row">
	        <div class="col-sm-8 col-md-7 py-4">
	          <h4 class="text-white">Sobre Nosotros</h4>
	          <p class="text-muted">Este sitio fue desarrollado por la comision 4 del Informatorio. Estamos aprendiendo Django</p>
	        </div>
	        <div class="col-sm-4 offset-md-1 py-4">
	          <h4 class="text-white">Opciones</h4>
	          <ul class="list-unstyled">
	          	{% if user.is_authenticated %}
					<li><a href="{% url 'logout' %}" class="text-white">Cerrar sesion</a></li>
				{% else %}
					<li><a href="{% url 'login' %}">Iniciar sesion</a></li>
				{% endif %}
	          </ul>
	        </div>
	      </div>
	    </div>
	  </div>
	  <div class="navbar navbar-dark bg-dark shadow-sm">
	    <div class="container">
	      <a href="{% url 'inicio' %}" class="navbar-brand d-flex align-items-center">
	        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
	        <strong>InforMarket</strong>
	      </a>
	      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	    </div>
	</div>
</header>

proyectofinalsustentable/templates/base/portada.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Bienvenido al Comercio Electronico del Info</h1>
        <p class="lead text-muted">Estamos desarrollando un sitio de comercio electronico en la comision 4.</p>
        <!--
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
    	-->
      </div>
    </div>
</section>

proyectofinalsustentable/templates/includes/form_errors.html
{% if form.errors %}
	{% for field in form %}
		{% for error in field.errors  %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  	<strong>{{field.label}}</strong> {{error}}
			  	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endfor %}

	{% endfor %}

	{% for error in form.non_field_errors  %}
		<div class="alert alert-warning alert-dismissible fade show" role="alert">
		  	{{error}}
		  	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	{% endfor %}
{% endif %}

proyectofinalsustentable/templates/inicio.html
{% extends "base/base.html" %}

{% block contenido %}
	<h1>Ofertas del Dia</h1>
      	<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      		{% for p in productos %}
	        	<div class="col">
	          		<div class="card shadow-sm">
	            		<svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

	            		<div class="card-body">
	              			<p class="card-text">{{p.nombre}}</p>
	              			<div class="d-flex justify-content-between align-items-center">
		                		<div class="btn-group">
		                  			<!--<button type="button" class="btn btn-sm btn-outline-secondary">View</button>-->
		                  			<a class="btn btn-sm btn-outline-secondary" href="{% url 'productos:detalle' %}">Ver mas</a>
		                		</div>
		                		<!--<small class="text-muted">9 mins</small>-->
	              			</div>
	            		</div>
	          		</div>
	        	</div>
        	{% endfor %}
     	</div>
{% endblock contenido %}

proyectofinalsustentable/templates/login.html
{% load static %}

<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<title>Login</title>

		<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/floating-labels/">

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

		<!-- Custom styles for this template -->
		<link href="{% static 'css/login.css' %}" rel="stylesheet">
	</head>

	<body>
		<form class="form-signin" method="POST">{% csrf_token %}
			<div class="text-center mb-4">
				<!-- 
				<img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
				-->
				<h1 class="h3 mb-3 font-weight-normal">Iniciar Sesion</h1>
				<p>Sitio de Compras Informarket</p>
			</div>

			{% include "includes/form_errors.html" %}
			<div class="form-label-group">
				<input type="text" id="inputUsername" class="form-control" placeholder="Ingrese nombre de usuario" required="" autofocus="" name="username">
				<label for="inputUsername">Nombre de usuario</label>
			</div>

			<div class="form-label-group">
				<input type="password" id="inputPassword" class="form-control" placeholder="Ingrese contraseña" required="" name="password">
				<label for="inputPassword">Contraseña</label>
			</div>

			<div class="checkbox mb-3">
				<label>
					<input type="checkbox" value="remember-me"> Recuerdame
				</label>
			</div>
			<button class="btn btn-lg btn-primary btn-block" type="submit" style="display: block; width: 100%;">Iniciar sesion</button>
			<p class="mt-5 mb-3 text-muted text-center"><a href="{% url 'inicio' %}">Ir al Inicio</a></p>
		</form>
	</body>
</html>

proyectofinalsustentable/templates/productos/admin/editar.html
{% extends "base/base.html" %}

{% block contenido %}
	<form method="POST">{% csrf_token %}
		{% include "includes/form_errors.html" %}
		
		{{form.as_p}}

		<div class="row">
			<div class="col">
				<button type="submit" class="btn btn-success">Guardar</button>
				<a href="{% url 'productos:admin_listar' %}" class="btn btn-danger">Cancelar</a>
			</div>
		</div>
	</form>
{% endblock contenido %}

proyectofinalsustentable/templates/productos/admin/listar.html
{% extends "base/base.html" %}

{% block contenido %}
	<div class="row" style="padding:10px;">
		<div class="col">
			<a href="{% url 'productos:admin_nuevo' %}" class="btn btn-success">Nuevo</a>
		</div>
	</div>
	

	<table class="table table-success table-striped">
		<thead>
			<th scope="col">Id</th>
			<th scope="col">Nombre</th>
			<th>Precio</th>
			<th scope="col">Acciones</th>
		</thead>
		<tbody>
			{% for p in productos %}
				<tr>
			      <th scope="row">{{p.id}}</th>
			      <td>{{p.nombre}}</td>
			      <td>$ {{p.precio}}</td>
			      <td>
			      	<a href="">Ver</a>
			      	<a href="{% url 'productos:admin_editar' p.id %}">Editar</a>
			      	<a href="">Eliminar</a>
			      </td>
			    </tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock contenido %}

proyectofinalsustentable/templates/productos/admin/nuevo.html
{% extends "base/base.html" %}

{% block contenido %}
	<form method="POST">{% csrf_token %}
		{% include "includes/form_errors.html" %}
		
		{{form.as_p}}

		<div class="row">
			<div class="col">
				<button type="submit" class="btn btn-success">Guardar</button>
				<a href="{% url 'productos:admin_listar' %}" class="btn btn-danger">Cancelar</a>
			</div>
		</div>
	</form>
{% endblock contenido %}

proyectofinalsustentable/templates/productos/detalle.html
{% extends "base/base.html" %}